{
 "title": "Kubernetes Monitoring (Expensy)",
 "panels": [
  {
   "title": "Uso de CPU (pods)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "rate(container_cpu_usage_seconds_total{image!=\"\"}[5m])",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Uso de Memoria (pods)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "container_memory_usage_bytes{image!=\"\"}",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Estado de Pods",
   "type": "bargauge",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "kube_pod_status_phase{phase!=\"Succeeded\"}",
     "legendFormat": "{{pod}} - {{phase}}"
    }
   ]
  }
 ]
}