apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
spec:
  replicas: 2
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/port: "8706"
        prometheus.io/path: "/metrics"  # cambia si tienes otro path o quítalo si es /metrics
    spec:
      containers:
        - name: backend
          image: gabrielariaskarausch/expensy-backend:latest
          ports:
            - containerPort: 8706
          env:
            - name: PORT
              value: "8706"
            - name: DATABASE_URI
              valueFrom:
                secretKeyRef:
                  name: backend-secrets
                  key: DATABASE_URI
            - name: REDIS_HOST
              value: "redis"
            - name: REDIS_PORT
              value: "6379"
            - name: REDIS_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: backend-secrets
                  key: REDIS_PASSWORD

