name: CI/CD Pipeline - Expensy

on:
  push:
    branches:
      - main
  pull_request:

env:
  REGISTRY: docker.io
  IMAGE_BACKEND: gabrielariaskarausch/expensy-backend
  IMAGE_FRONTEND: gabrielariaskarausch/expensy-frontend

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Log in to DockerHub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Build and push backend image
      uses: docker/build-push-action@v5
      with:
        context: ./expensy_backend
        file: ./expensy_backend/Dockerfile
        push: true
        tags: ${{ env.IMAGE_BACKEND }}:latest

    - name: Build and push frontend image
      uses: docker/build-push-action@v5
      with:
        context: ./expensy_frontend
        file: ./expensy_frontend/Dockerfile
        push: true
        tags: ${{ env.IMAGE_FRONTEND }}:latest

    - name: Set up kubectl
      uses: azure/setup-kubectl@v3
      with:
        version: v1.28.0

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v2
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: us-west-1

    - name: Update kubeconfig
      run: aws eks update-kubeconfig --name expensy-cluster

    - name: Deploy to EKS
      run: |
        kubectl apply -f k8s/backend-deployment.yaml
        kubectl apply -f k8s/backend-service.yaml
        kubectl apply -f k8s/frontend-deployment.yaml
        kubectl apply -f k8s/frontend-service.yaml
